"""Fail-closed validation shared by ScanLan reconstruction backends."""

from .engine import (
    VALIDATION_CONTRACT_VERSION,
    CameraValidationConfig,
    CameraValidationResult,
    DepthValidationConfig,
    DepthValidationResult,
    GeometryValidationConfig,
    GeometryValidationResult,
    RayConsistencyResult,
    ScaleValidationConfig,
    ScaleValidationResult,
    SimilarityTransform,
    validate_camera_trajectory,
    validate_depth,
    validate_geometry,
    validate_ray_depths,
    validate_scale,
)
from .backend_policy import (
    BACKEND_POLICY_VERSION,
    BENCHMARK_MANIFEST_VERSION,
    BackendPolicyError,
    load_benchmark_manifest,
    packaged_benchmark_manifest_path,
    select_backend_policy,
)

__all__ = [
    "VALIDATION_CONTRACT_VERSION",
    "CameraValidationConfig",
    "CameraValidationResult",
    "DepthValidationConfig",
    "DepthValidationResult",
    "GeometryValidationConfig",
    "GeometryValidationResult",
    "RayConsistencyResult",
    "ScaleValidationConfig",
    "ScaleValidationResult",
    "SimilarityTransform",
    "validate_camera_trajectory",
    "validate_depth",
    "validate_geometry",
    "validate_ray_depths",
    "validate_scale",
    "BACKEND_POLICY_VERSION",
    "BENCHMARK_MANIFEST_VERSION",
    "BackendPolicyError",
    "load_benchmark_manifest",
    "packaged_benchmark_manifest_path",
    "select_backend_policy",
]
